### ISSUE TITLE
移动端  后台底部  必读说明  下面那三个带颜色的按钮  不能自适应  导致整个页面失去焦点

### ISSUE THREAD

**Issue by mzljjkj** [Baiyuetribe/kamiFaka#103]
1. BUG反馈请描述最小复现步骤

2. 普通问题：99%的答案都在帮助文档里，请仔细阅读https://kmfaka.baklib-free.com/

3. 新功能新概念提交：请文字描述或截图标注

**Comment by Baiyuetribe** [comment]
非移动端适配
