### ISSUE TITLE
没有Linux手动安装教程吗？

### ISSUE THREAD

**Issue by zhujitop** [Baiyuetribe/kamiFaka#107]
没接触过docker，也没用面板。
我服务器本身已经有其他网站在运行了，nginx、php、mysql这些都安装好的。

按照这里的教程进行了安装：https://baiyue.one/archives/1700.html

下面是安装显示结果：
`docker run -itd --name kamifaka -p 8000:8000 --restart always registry.cn-hangzhou.aliyuncs.com/baiyuetribe/kamifaka
Unable to find image 'registry.cn-hangzhou.aliyuncs.com/baiyuetribe/kamifaka:latest' locally
latest: Pulling from baiyuetribe/kamifaka
f7ec5a41d630: Pull complete 
6f318b7b4c32: Pull complete 
65be07e2a755: Pull complete 
d843bb564d1d: Pull complete 
044f430d907f: Pull complete 
4dde1a48676b: Pull complete 
25c4de865f83: Pull complete 
da908a6aeb12: Pull complete 
440bb99d87ca: Pull complete 
886250e3939b: Pull complete 
Digest: sha256:c209d3e8d8a3e80bec043dfc1176c3f5abe9dabc8494e5e6be80a542184cfef5
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/baiyuetribe/kamifaka:latest
66324ddabe84e701ef9e572ff2d7dc2a1334a28922de209c83c0136684731f3a
`
然后想用现有的nginx去配置，就没找到怎么弄了。

全盘搜索kamifaka、baiyuetribe都没有。
docker是没有这些的吗？
倒是搜索出来docker相关所在的文件夹和文件了。

本来想用这个卸载了：
`docker rm -f kamifaka && docker rmi -f baiyuetribe/kamifaka`

又提示：
Error: No such container: kamifaka
Error: No such image: baiyuetribe/kamifaka

请问现在怎么卸载整个docker和相关文件呢？
看了下docker.sh里面只有安装，没卸载。
服务器配置低，没折腾上，所以还是都卸载了吧...

用外面的教程也能卸载吗？比如
`yum remove docker-ce.x86_64 -y`
然后删掉相关文件夹？

因为是用的您的脚本，还是先问下。

**Comment by Baiyuetribe** [comment]
一开始操作就有问题，linux手动部署请参考开发文档。正式安装请参考博客里写的两篇教程
