### ISSUE TITLE
关于能否直接使用源码部署不使用docker的问题

### ISSUE THREAD

**Issue by zhjurz** [Baiyuetribe/kamiFaka#136]
请问能不能直接用源码部署发卡系统，这样感觉会更方便一些，希望能出个教程，谢谢大佬

**Comment by Baiyuetribe** [comment]
> 请问能不能直接用源码部署发卡系统，这样感觉会更方便一些，希望能出个教程，谢谢大佬
开发环境为python3.9。目前普通使用的宝塔环境为3.7。使用docker是为了独立运行环境。直接运行python也是一样的，确保python环境为3.9+，然后参考dockerfile启动就行。
