### ISSUE TITLE
有没有arm64架构的docker镜像？

### ISSUE THREAD

**Issue by While-Shark** [Baiyuetribe/kamiFaka#147]
有没有arm64架构的docker镜像？

**Comment by Baiyuetribe** [comment]
需要自行克隆后构建，构建时注意Python版本依赖

**Comment by While-Shark** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
