### ISSUE TITLE
手机开后台不显示菜单

### ISSUE THREAD

**Issue by zqcthegreat** [Baiyuetribe/kamiFaka#2]
手机进后台只显示后台首页，没有菜单栏。电脑没试

**Comment by Baiyuetribe** [comment]
感谢反馈，PC端左侧菜单正常，移动端扩展菜单失效，已尝试修复，疑似与js控制有关，待解决。当然你也可以设置手机浏览器模式为Pc模式，然后进行浏览。

**Comment by Baiyuetribe** [comment]
原生js控制失败，所以我用vue3实现了移动端菜单显示，单独加了个按钮（仅移动模式下显示）。该问题现已修复
![image](https://user-images.githubusercontent.com/43716063/98119598-c8330e80-1ee7-11eb-99e8-c3713809201f.png)
