### ISSUE TITLE
payjs 微信二维码调用失败

### ISSUE THREAD

**Issue by BeyondIM** [Baiyuetribe/kamiFaka#73]
![](https://img.vim-cn.com/9c/6366b9de13a8a2bb17b81afe9f1af742df6159.jpg)

已经确认 mchid 和 payjs_key 正确。
在 1.6 下正常，升级到 1.83 后存在上述错误。

地址：https://store.dig77.com

**Comment by Baiyuetribe** [comment]
1.87都已经快一个月了，如何升级的？
