### ISSUE TITLE
建议新功能：通过HTTP API提卡

### ISSUE THREAD

**Issue by Admin6016** [Baiyuetribe/kamiFaka#83]
个人有需求希望增加HTTP API请求提卡，类似于彩虹发卡。
建议功能可以选择GET或POST提卡，增加选项是否将返回内容作为卡密。
URL请求中带订单参数的模板，如：
http://127.0.0.1:8080?orderId=${oid}&price=${price}&kind=${shopkind}

**Comment by Baiyuetribe** [comment]
系统采用前后端分离模式开发，实际上就是调用API实现前端业务，你说的功能非常容易实现，但是不符合大众需求，可独立定制下
