### ISSUE TITLE
几个bug与新功能的建议

### ISSUE THREAD

**Issue by Ansetheisia** [Baiyuetribe/kamiFaka#96]
BUG1：邮箱昵称设置了压根没用，发件人姓名是发件邮箱@前的内容
BUG2：从编辑商品的编辑器页面直接返回时，鼠标滚轮滑动网页功能失效

建议1：添加验证码系统，不是腾讯云这类让同行恶意刷房子赔进去的验证码，尽量是recaptcha或者hcaptcha这类**免费**并且还不是**过于过分**的验证码。（点名epic和origin的数骰子
建议2：添加优惠劵系统，可以设定单张优惠劵优惠金额或优惠折扣，限制最低使用额，限制使用商品。
建议3：改进批发价系统：虽说能看懂，但是还是有点麻烦，可以参考值联云卡的 件数=批发价的设置
（举个例子 5=2.8 也就是满五件每件2.8元）

**Comment by yangyzp** [comment]
“发件人昵称”这个问题确定是个bug

**Comment by Baiyuetribe** [comment]
未来的商用版已全部实现，开源版仅作必要更新
