### ISSUE TITLE
服务器迁移如何备份恢复

### ISSUE THREAD

**Issue by alimalls** [Baiyuetribe/kamiFaka#97]
作者你好，使用你这个发卡系统后，觉得非常好用，我现在是用宝塔的docker搭建的，就是想问下，如果我更换服务器了，怎么备份原来的数据，还原到新的服务器上，我在后台看到只有恢复订单数据的。谢谢

**Comment by Baiyuetribe** [comment]
宝塔数据库，备份现有的数据库，然后本地保存下来；新服务器搭建后，再次到宝塔数据库覆盖导入即可

**Comment by alimalls** [comment]
> 宝塔数据库，备份现有的数据库，然后本地保存下来；新服务器搭建后，再次到宝塔数据库覆盖导入即可

我没有用到数据库哦，用的是你程序自带的。

**Comment by Baiyuetribe** [comment]
那就好好参考文档。https://kmfaka.baklib-free.com/a533/f977
